version: 0.2
phases:
  install:
    commands:
      - pip install git-remote-codecommit
  build:
    commands:
       - env
       - git clone -b $REFERENCE_NAME codecommit::$REPO_REGION://$REPOSITORY_NAME
       - dt=$(date '+%d-%m-%Y-%H:%M:%S');
       - echo "$dt"
       - object=$dt-$REPOSITORY_NAME-$COMMIT_ID
       - zip -yr $object.zip ./
       - aws s3 cp $object.zip s3://$BUCKET/$REPOSITORY_NAME/
